name: Compile protobuf stubs

on:
  push:
    branches: [master]

jobs:
  # This workflow contains a single job called "compile"
  compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Install dependencies
    steps:
      - name: Set up Go 1.15.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install protoc-gen-go and protoc-gen-go-grpc
        run: |
          export GO111MODULE=on
          go get google.golang.org/protobuf/cmd/protoc-gen-go
          git clone -b v1.31.0 https://github.com/grpc/grpc-go
          cd grpc-go/cmd/protoc-gen-go-grpc
          go install .

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Compile Go stubs
        run: make go

      - name: Documentation
        run: make doc

      - name: Commit generated stubs
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git add generated
          git add docs
          git commit -m "Automated: Update protobuf stubs"
          git push
